<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="1R-22" name="Default test" tests="7" failures="1" timestamp="1 Feb 2019 14:24:28 GMT" time="1920.957" errors="0">
  <testcase name="feature" time="103.499" classname="org.drc.vat.StepDefinitions.TestRunner"/>
  <testcase name="feature" time="267.076" classname="org.drc.vat.StepDefinitions.TestRunner"/>
  <testcase name="feature" time="401.493" classname="org.drc.vat.StepDefinitions.TestRunner"/>
  <testcase name="feature" time="331.607" classname="org.drc.vat.StepDefinitions.TestRunner"/>
  <testcase name="feature" time="453.212" classname="org.drc.vat.StepDefinitions.TestRunner"/>
  <testcase name="feature" time="15.776" classname="org.drc.vat.StepDefinitions.TestRunner"/>
  <testcase name="feature" time="347.394" classname="org.drc.vat.StepDefinitions.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [Payment Not Completed] but found []">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Payment Not Completed] but found []
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Payment Not Completed] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at org.drc.vat.StepDefinitions.DebtCollectionCaseScreen.status_should_be_displayed(DebtCollectionCaseScreen.java:91)
	at âœ½.Then Status "Payment Not Completed" should be displayed(src/test/resources/features/37_NotificationPopUp.feature:45)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
